language: C

os:
  - linux
  # - osx

dist: trusty

compiler:
  - clang
  - gcc
  
before_install:
  - pip install --user python-numpy subprocess32, numpy, six, cycler, python-dateutil, functools32, pytz, pyparsing, matplotlib
  
script: ./configure && make && make test

