language: C

os:
  - linux
  # - osx

dist: trusty

compiler:
  - clang
  - gcc
  
before_install:
  - sudo apt-get install python-tk python-numpy
  # - pip install --user subprocess32 numpy cycler python-dateutil functools32 pytz pyparsing matplotlib
  
script: ./configure && make && make test

